const characters = [

        {
        id: 11,
        thumb: "/im/Sprites/Vivian.png",
        image: "/im/refs/Vivian.png",
        name: "VIVIAN",
        desc: "Bound of Greed",
        link: "./characters/vivian.html",
        type: ["Bound"],
        tags: [ "Greed Arc", ],
        color: "yellow",
        finished: true,
        logo: "./im/logos/vivian.svg",
        },

        {
        id: 12,
        thumb: "/im/Sprites/Zero.png",
        image: "/im/refs/Zero.png",
        name: "ZERO",
        desc: "Bound of Charity",
        link: "./characters/zero.html",
        type: ["Bound", "sex"],
        tags: [ "Greed Arc"],
        color: "yellow",
        finished: true,
        logo: "./im/logos/zero.svg",

    },
        {
        id: 13,
        thumb: "/im/Sprites/Porter.png",
        image: "/im/refs/Porter.png",
        name: "PORTER",
        desc: "Avatar of Greed",
        link: "./characters/porter.html",
        type: [ "Avatar"],
        tags: [ "Greed Arc"],
        color: "yellow",
        finished: false,
        logo: "./im/logos/porter.svg",

    },
        {
        id: 14,
        thumb: "/im/Sprites/Marty.png",
        image: "/im/refs/Marty.png",
        name: "MARTY",
        desc: "???",
        type: ["Supporting"],
        link: "./characters/marty.html",
        tags: [ "Greed Arc"],
        color: "yellow",
        finished: false,
        logo: "./im/logos/marty.svg",
    },
        {
        id: 15,
        thumb: "/im/Sprites/Stu.png",
        image: "/im/refs/Stu.png",
        name: "STU",
        desc: "????.",
        link: "./characters/stu.html",
        type: ["Supporting", "Supporting"],
        tags: [ "Greed Arc",  ],
        color: "yellow",
            logo: "./im/logos/stu.svg",
        finished: false,
    },

    {
        id: 16,
        thumb: "/im/Sprites/Hermann.png",
        image: "/im/refs/Hermann.png",
        name: "HERMANN",
        desc: "????.",
        link: "./characters/hermann.html",
        type: ["Supporting", "Supporting"],
        tags: [ "Greed Arc",],
        color: "yellow",
            logo: "./im/logos/hermann.svg",
        finished: false,
    },

    {
        id: 17,
        thumb: "/im/Sprites/Poppy.png",
        image: "/im/refs/Poppy.png",
        name: "POPPY",
        desc: "????.",
        link: "./characters/poppy.html",
        type: ["Supporting", "Supporting"],
        tags: [ "Greed Arc",],
        color: "yellow",
        finished: false,
    },
    {
        id: 18,
        thumb: "/im/Sprites/Rufina.png",
        image: "/im/refs/Rufina.png",
        name: "RUFINA",
        desc: "????.",
        link: "./characters/rufina.html",
        type: ["Supporting", ],
        tags: [ "Greed Arc", "Pride Arc",],
        color: "yellow",
        finished: true,
    },

    {
        id: 22,
        thumb: "/im/Sprites/Lydia.png",
        image: "/im/refs/Lydia.png",
        name: "LYDIA",
        desc: "Bound of Diligence",
        type: ["Bound"],
        link: "./characters/lydia.html",
        tags: [ "Sloth Arc"],
        color: "blue",
        finished: false,
    },
    {
        id: 21,
        thumb: "/im/Sprites/Odelle.png",
        image: "/im/refs/Odelle.png",
        name: "odelle",
        desc: "Bound of Sloth",
        type: ["Bound"],
        link: "./characters/odelle.html",
        tags: [ "Sloth Arc"],
        color: "blue",
        finished: false,
    },
        {
        id: 23,
        thumb: "/im/Sprites/Ahab.png",
        image: "/im/refs/Ahab.png",
        name: "Ahab",
        desc: "Bound of Sloth",
        type: ["Bound"],
        link: "./characters/ahab.html",
        tags: [ "Sloth Arc"],
        color: "blue",
        finished: true,
    },

    {
        id: 24,
        thumb: "/im/Sprites/Alice.png",
        image: "/im/refs/Alice.png",
        name: "alice",
        desc: "Avatar of Sloth",
        type: [ "Avatar"],
        link: "./characters/alice.html",
        tags: [ "Sloth Arc"],
        color: "blue",
        finished: false,
    },
    {
        id: 25,
        thumb: "/im/Sprites/Wart.png",
        image: "/im/refs/Wart.png",
        name: "wart",
        desc: "????.",
        link: "./characters/wart.html",
        type: ["Supporting"],
        tags: [ "Sloth Arc", ],
        color: "blue",
        finished: false,
    },
    {
        id: 26,
        thumb: "/im/Sprites/Tiam.png",
        image: "/im/refs/Tiam.png",
        name: "TIAM",
        desc: "??.",
        link: "./characters/tiam.html",
        type: ["Supporting", "Supporting"],
        tags: [ "Sloth Arc"],
        color: "blue",
        finished: true,
    },
    {
        id: 31,
        thumb: "/im/Sprites/Illauq.png",
        image: "/im/refs/Illauq.png",
        name: "ILLAUQ",
        desc: "Bound of Patience",
        link: "./characters/illauq.html",
        type: ["Bound"],
        tags: [ "Wrath Arc"],
        color: "red",
            logo: "./im/logos/illauq.svg",
        finished: true,
    },
    {
        id: 32,
        thumb: "/im/Sprites/Olga.png",
        image: "/im/refs/Olga.png",
        name: "OLGA",
        desc: "Bound of WRATH",
        link: "./characters/olga.html",
        type: ["Bound"],
        tags: [ "Wrath Arc"],
        color: "red",
            logo: "./im/logos/olga.svg",
        finished: false,
    },

    {
        id: 33,
        thumb: "/im/Sprites/Ryusuke.png",
        image: "/im/refs/Ryusuke.png",
        name: "RYUSUKE",
        desc: "Avatar of Wrath",
        link: "./characters/ryusuke.html",
        type: [ "Supporting"],
        tags: [ "Wrath Arc"],
        color: "red",
        finished: false,
    },
    
    {
        id: 34,
        thumb: "/im/Sprites/Yael.png",
        image: "/im/refs/Yael.png",
        name: "YAEL",
        desc: "???",
        link: "./characters/yael.html",
        type: [ "Supporting"],
        tags: [ "Wrath Arc"],
        color: "red",
        finished: true,
    },

    
    {
        id: 35,
        thumb: "/im/Sprites/Wip.png",
        image: "/im/refs/Wip.png",
        name: "BRIDGETTE",
        desc: "???",
        link: "./characters/bridgette.html",
        type: [ "Supporting"],
        tags: [ "Wrath Arc"],
        color: "red",
        finished: false,
    },
        {
        id: 36,
        thumb: "/im/Sprites/Wip.png",
        image: "/im/refs/Wip.png",
        name: "VERONICA",
        desc: "???",
        link: "./characters/veronica.html",
        type: [ "Avatar"],
        tags: [ "Wrath Arc"],
        color: "red",
        finished: false,
    },


    {
        id: 41,
        thumb: "/im/Sprites/Rae.png",
        image: "/im/refs/Rae.png",
        name: "RAE",
        desc: "Bound of Chastity",
        link: "./characters/rae.html",
        type: ["Bound"],
        tags: ["Lust Arc", ],
        color: "purple",
        finished: true,
            logo: "./im/logos/rae.svg",

        
    },
    {
        id: 42,
        thumb: "/im/Sprites/Weirdo.png",
        image: "/im/refs/Weirdo.png",
        name: "WEIRDO",
        desc: "Bound of Lust",
        link: "./characters/weirdo.html",
        type: ["Bound"],
        tags: ["Lust Arc", ],
        color: "purple",
        finished: true,
            logo: "./im/logos/weirdo.svg",
    },

    {
        id: 43,
        thumb: "/im/Sprites/Arvid.png",
        image: "/im/refs/Arvid.png",
        name: "ARVID",
        desc: "???.",
        link: "./characters/arvid.html",
        type: [ "Avatar"],
        tags: [ "Lust Arc", ],
        color: "purple",
        finished: true,
    },
    {
        id: 44,
        thumb: "/im/Sprites/Dev.png",
        image: "/im/refs/Dev.png",
        name: "DEV",
        desc: "???",
        link: "./characters/dev.html",
        type: ["Supporting"],
        tags: ["Lust Arc", ],
        color: "purple",
        finished: true,
            logo: "./im/logos/dev.svg",
    },


    {
        id: 45,
        thumb: "/im/Sprites/Yams.png",
        image: "/im/refs/Yams.png",
        name: "YAMS",
        desc: "???.",
        link: "./characters/yams.html",
        type: ["Supporting"],
        tags: ["Lust Arc", ],
        color: "purple",
        finished: false,
    },

    {
        id: 51,
        thumb: "/im/Sprites/Dallas.png",
        image: "/im/refs/Dallas.png",
        name: "dallas",
        desc: "Bound of Gluttony",
        link: "./characters/dallas.html",
        type: ["Bound"],
        tags: [ "Gluttony Arc", ],
        color: "green",
        finished: true,
        logo: "./im/logos/dallas.svg",
    },
    {
        id: 52,
        thumb: "/im/Sprites/Wermer.png",
        image: "/im/refs/Wermer.png",
        name: "wermer",
        desc: "Bound of Temperance",
        link: "./characters/wermer.html",
        type: ["Bound"],
        tags: [ "Gluttony Arc", ],
        color: "green",
        finished: true,
        logo: "./im/logos/wermer.svg",

    },
    {
        id: 53,
        thumb: "/im/Sprites/Groodus.png",
        image: "/im/refs/Groodus.png",
        name: "groodus",
        desc: "Avatar of Gluttony",
        link: "./characters/groodus.html",
        type: [ "Avatar"],
        tags: [ "Gluttony Arc"],
        color: "green",
        finished: true,
    },

    {
        id: 54,
        thumb: "/im/Sprites/Walter.png",
        image: "/im/refs/Walter.png",
        name: "walter",
        desc: "???.",
        link: "./characters/walter.html",
        type: ["Supporting"],
        tags: [ "Gluttony Arc", ],
        color: "green",
        finished: false,
    },
    {
        id: 55,
        thumb: "/im/Sprites/Macleod.png",
        image: "/im/refs/Macleod.png",
        name: "macleod",
        desc: "???.",
        link: "./characters/macleod.html",
        type: ["Supporting", "Supporting"],
        tags: [  "Gluttony Arc"],
        color: "green",
        finished: true,
    },
    {
        id: 56,
        thumb: "/im/Sprites/Moose.png",
        image: "/im/refs/Moose.png",
        name: "moose",
        desc: "???.",
        link: "./characters/moose.html",
        type: ["Supporting"],
        tags: [  "Gluttony Arc"],
        color: "green",
        finished: false,

    },
        {
        id: 57,
        thumb: "/im/Sprites/Wip.png",
        image: "/im/refs/Wip.png",
        name: "SYBIL",
        desc: "????.",
        link: "./characters/sybil.html",
        type: ["Supporting"],
        tags: [ "Gluttony Arc",],
        color: "yellow",
        finished: false,
    },


    {
        id: 61,
        thumb: "/im/Sprites/Carl.png",
        image: "/im/refs/Carlisle.png",
        name: "carlisle",
        desc: "Bound of Kindness",
        link: "./characters/carlisle.html",
        type: ["Bound"],
        finished: false,
        tags: [ "Envy Arc", ],
        color: "orange",

    },

    {
        id: 62,
        thumb: "/im/Sprites/Cue.png",
        image: "/im/refs/Cue.png",
        name: "cue",
        desc: "???.",
        link: "./characters/cue.html",
        type: ["Bound"],
        finished: false,
        tags: [ "Envy Arc", ],
        color: "orange",
    },
    
            {
        id: 63,
        thumb: "/im/Sprites/Hugo.png",
        image: "/im/refs/Hugo.png",
        name: "HUGO",
        desc: "????.",
        link: "./characters/hugo.html",
        type: ["Avatar"],
        tags: [ "Envy Arc",],
        color: "orange",
        finished: false,
    },

    {
        id: 64,
        thumb: "/im/Sprites/Isaac.png",
        image: "/im/refs/Isaac.png",
        name: "isaac",
        desc: "???.",
        link: "./characters/isaac.html",
        type: ["Supporting"],
        finished: false,
        tags: [ "Envy Arc", ],
        color: "orange",
    },
    
            {
        id: 65,
        thumb: "/im/Sprites/Mary.png",
        image: "/im/refs/Mary.png",
        name: "MARY",
        desc: "????.",
        link: "./characters/mary.html",
        type: ["Supporting"],
        tags: [ "Envy Arc",],
        color: "orange",
        finished: false,
    },



            {
        id: 73,
        thumb: "/im/Sprites/Wip.png",
        image: "/im/refs/Wip.png",
        name: "TAU",
        desc: "????.",
        link: "./characters/tau.html",
        type: ["Bound"],
        tags: [ "Pride Arc",],
        color: "teal",
        finished: false,
    },
            {
        id: 73,
        thumb: "/im/Sprites/Wip.png",
        image: "/im/refs/Wip.png",
        name: "CLARK",
        desc: "????.",
        link: "./characters/clark.html",
        type: ["Bound"],
        tags: [ "Pride Arc",],
        color: "teal",
        finished: false,
    },


            {
        id: 73,
        thumb: "/im/Sprites/Sheen.png",
        image: "/im/refs/Wip.png",
        name: "SHEEN",
        desc: "????.",
        link: "./characters/sheen.html",
        type: ["Avatar"],
        tags: [ "Pride Arc",],
        color: "teal",
        finished: false,
    },

                {
        id: 73,
        thumb: "/im/Sprites/Wip.png",
        image: "/im/refs/Wip.png",
        name: "RANDY",
        desc: "????.",
        link: "./characters/randy.html",
        type: ["Supporting"],
        tags: [ "Pride Arc",],
        color: "teal",
        finished: false,
    },


    
    
    
    
    

];


